# Generated by Django 4.2.4 on 2023-08-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_custompermission'),
        ('demoapp', '0016_delete_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_permissions', to='auth.permission')),
                ('main_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_permissions', to='auth.permission')),
            ],
        ),
    ]
