# Generated by Django 4.2.4 on 2023-08-28 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_custompermission'),
        ('demoapp', '0017_permissionrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('source_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_custom_permissions', to='auth.permission')),
            ],
        ),
    ]
