# Generated by Django 4.2.4 on 2023-08-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0019_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
